<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>CHL5202: Biostatistics II</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Kevin Dang</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-university"></span>
     
    Teaching
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="CHL5202.html">
        <span class="fa fa-book"></span>
         
        CHL5202 - Winter 2022
      </a>
    </li>
    <li>
      <a href="STA238.html">
        <span class="fa fa-book"></span>
         
        STA238 - Winter 2022
      </a>
    </li>
    <li>
      <a href="STA237.html">
        <span class="fa fa-book"></span>
         
        STA237 - Fall 2021
      </a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-project-diagram"></span>
     
    Projects
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="cognitive.html">
        <span class="fa fa-code"></span>
         
        Cognitive Flexibility
      </a>
    </li>
    <li>
      <a href="EDA.html">
        <span class="fa fa-code"></span>
         
        Exploratory Data Analysis
      </a>
    </li>
    <li>
      <a href="heart.html">
        <span class="fa fa-code"></span>
         
        Heart Disease Classifier
      </a>
    </li>
    <li>
      <a href="mice.html">
        <span class="fa fa-code"></span>
         
        Mice Protein Expression
      </a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">
    <span class="fa fa-user"></span>
     
    About Me
  </a>
</li>
<li>
  <a href="files/Resume_Kevin_Dang.pdf">
    <span class="fa fa-file-pdf-o"></span>
     
    Resume
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">CHL5202: Biostatistics II</h1>

</div>


<div id="course-description-and-objectives" class="section level1 unlisted unnumbered">
<h1 class="unlisted unnumbered">Course Description and Objectives</h1>
<ul>
<li>The goal of this course is to continue development and application of skills in statistical analysis required in epidemiologic and health care research.</li>
<li>Analysis where outcome is continuous and exposure and covariates are a mix of continuous and categorical variables (multiple linear regression)</li>
<li>Relaxing linearity assumptions of continuous exposure variables through the use of regression splines</li>
<li>Perform internal validation by means of bootstrapping or cross-validation</li>
<li>Extension to binary outcomes (multiple logistic regression)</li>
<li>Extension to time to event and censored outcomes (survival analysis)</li>
<li>Dealing with missing data</li>
<li>Introduce Bayesian methods</li>
</ul>
<p>Course material provided by Professor Kevin Thorpe and modifications were made by myself.</p>
</div>
<div id="tutorial-1" class="section level1">
<h1>Tutorial 1</h1>
<div id="question-1" class="section level2">
<h2>Question 1</h2>
<p>Load the data frame <code>tut1</code> into R from the file <code>tut1.RData</code> available on the course page. The data frame contains the variables x and y.</p>
<p>Fit a simple regression with y as the response and x as the predictor. Use diagnostic plots to determine if a non-linear relationship should be modeled. If you believe a non-linear relationship is present, model it using a restricted cubic spline. The number of knots is up to you.</p>
<pre class="r"><code># Load packages and data
library(rms)

load(&quot;./CHL5202/tut1.RData&quot;)

dd &lt;- datadist(tut1)
options(datadist=&quot;dd&quot;)</code></pre>
<ul>
<li><p>Some notes taken from <a href="https://thomaselove.github.io/432-notes/using-ols-from-the-rms-package-to-fit-linear-models.html">here</a>.</p></li>
<li><p>Comparing <code>ols()</code> vs <code>lm()</code>: one advantage for ols is that the entire variance-covariance matrix is saved</p></li>
</ul>
<pre class="r"><code>fit0 &lt;- ols(y~x,data=tut1)
fit0</code></pre>
<pre><code>## Linear Regression Model
##  
##  ols(formula = y ~ x, data = tut1)
##  
##                  Model Likelihood    Discrimination    
##                        Ratio Test           Indexes    
##  Obs     100    LR chi2     32.07    R2       0.274    
##  sigma1.0827    d.f.            1    R2 adj   0.267    
##  d.f.     98    Pr(&gt; chi2) 0.0000    g        0.769    
##  
##  Residuals
##  
##       Min       1Q   Median       3Q      Max 
##  -2.21787 -0.73287  0.02416  0.74941  2.75329 
##  
##  
##            Coef    S.E.   t     Pr(&gt;|t|)
##  Intercept  1.2185 0.2149  5.67 &lt;0.0001 
##  x         -0.3597 0.0591 -6.09 &lt;0.0001 
## </code></pre>
<ul>
<li>When applying anova to an ols model, it separates out the linear and non-linear components of restricted cubic splines and polynomial terms (and product terms if they are present).</li>
<li>Unlike for <code>lm()</code>, using <code>anova</code> with <code>ols()</code> we have partial F-tests that describe the marginal impact of removing each covariate from the model.</li>
</ul>
<pre class="r"><code>anova(fit0)</code></pre>
<pre><code>##                 Analysis of Variance          Response: y 
## 
##  Factor     d.f. Partial SS MS        F     P     
##  x           1    43.43251  43.432506 37.05 &lt;.0001
##  REGRESSION  1    43.43251  43.432506 37.05 &lt;.0001
##  ERROR      98   114.88584   1.172305</code></pre>
<ul>
<li>Next, we check the model assumptions using diagnostic plots.</li>
<li>In the Normal Q-Q Plot we are looking for normally distributed error terms, i.e. most of the points lie on the line and do not show a non-linear pattern.</li>
</ul>
<pre class="r"><code># for diagnostic plots
dx0 &lt;- data.frame(tut1, e = resid(fit0), yhat = fitted(fit0)) 

# Normal QQ Plot
qqnorm(dx0$e)
qqline(dx0$e)</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<ul>
<li><code>xyplot()</code>: Common Bivariate Trellis Plots. Produces conditional scatterplots, typically between two continuous variables. Below we have residual plots.</li>
<li>We are looking for the residuals to not show a distinct (non-linear) pattern which would suggest that a transformation is required.</li>
</ul>
<pre class="r"><code># Residual Plots
xyplot(e~x, data = dx0, type = c(&quot;p&quot;,&quot;smooth&quot;))</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>xyplot(e~yhat, data = dx0, type = c(&quot;p&quot;,&quot;smooth&quot;))</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<ul>
<li>A non-linear relationship is present, so we will model it using a restricted cubic spline. For this example, we are going to use 4 knots.</li>
</ul>
<pre class="r"><code>fit1 &lt;- ols(y ~ rcs(x, 4), data = tut1)

fit1</code></pre>
<pre><code>## Linear Regression Model
##  
##  ols(formula = y ~ rcs(x, 4), data = tut1)
##  
##                  Model Likelihood    Discrimination    
##                        Ratio Test           Indexes    
##  Obs     100    LR chi2     46.60    R2       0.372    
##  sigma1.0173    d.f.            3    R2 adj   0.353    
##  d.f.     96    Pr(&gt; chi2) 0.0000    g        0.875    
##  
##  Residuals
##  
##      Min      1Q  Median      3Q     Max 
##  -2.0412 -0.7268  0.1088  0.5716  2.3664 
##  
##  
##            Coef    S.E.   t     Pr(&gt;|t|)
##  Intercept  0.2834 0.3389  0.84 0.4050  
##  x          0.6559 0.2760  2.38 0.0195  
##  x&#39;        -3.3087 0.8566 -3.86 0.0002  
##  x&#39;&#39;        9.3222 2.4876  3.75 0.0003  
## </code></pre>
<ul>
<li>It is difficult to interpret the coefficients above. The <code>anova()</code> output below is more useful and shows a significant non-linear component.</li>
</ul>
<pre class="r"><code>anova(fit1)</code></pre>
<pre><code>##                 Analysis of Variance          Response: y 
## 
##  Factor     d.f. Partial SS MS        F     P     
##  x           3   58.97203   19.657342 19.00 &lt;.0001
##   Nonlinear  2   15.53952    7.769761  7.51 9e-04 
##  REGRESSION  3   58.97203   19.657342 19.00 &lt;.0001
##  ERROR      96   99.34632    1.034858</code></pre>
<pre class="r"><code># Plot predicted fit with confidence interval
ggplot(Predict(fit1))</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code># for diagnostic plots
dx1 &lt;- data.frame(tut1, e = resid(fit1), yhat = fitted(fit1))

# Normal QQ Plot
qqnorm(dx1$e)
qqline(dx1$e)</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre class="r"><code># Residual plots
xyplot(e ~ x, data = dx1, type = c(&quot;p&quot;, &quot;smooth&quot;))</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre class="r"><code>xyplot(e ~ yhat, data = dx1, type = c(&quot;p&quot;, &quot;smooth&quot;))</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-10-2.png" width="672" /></p>
<ul>
<li>There is no longer a non-linear pattern in the residuals.</li>
</ul>
</div>
<div id="question-2" class="section level2">
<h2>Question 2</h2>
<p>Load the data frame FEV from the file FEV.RData. For these data, use the variable fev as the response and the rest as the explanatory covariates.</p>
<p>Fit an additive linear model to fev using the other variables as the covariates. Evaluate whether any of the continuous variables should be fit as non-linear terms.</p>
<p>Fit an another additive model but this time model the continuous covariates with restricted cubic splines with four knots. Describe the results.</p>
<pre class="r"><code>load(&quot;./CHL5202/FEV.RData&quot;)

fev.dd &lt;- datadist(FEV)
options(datadist = &quot;fev.dd&quot;)</code></pre>
<pre class="r"><code># `dplyr()`: package for data wrangling - part of `tidyverse()`
library(dplyr)

# Useful for quickly viewing the data
glimpse(FEV)</code></pre>
<pre><code>## Rows: 654
## Columns: 6
## $ id     &lt;int&gt; 301, 451, 501, 642, 901, 1701, 1752, 1753, 1901, 1951, 1952, 20~
## $ age    &lt;int&gt; 9, 8, 7, 9, 9, 8, 6, 6, 8, 9, 6, 8, 8, 8, 8, 7, 5, 6, 9, 9, 5, ~
## $ fev    &lt;dbl&gt; 1.708, 1.724, 1.720, 1.558, 1.895, 2.336, 1.919, 1.415, 1.987, ~
## $ height &lt;dbl&gt; 57.0, 67.5, 54.5, 53.0, 57.0, 61.0, 58.0, 56.0, 58.5, 60.0, 53.~
## $ sex    &lt;fct&gt; female, female, female, male, male, female, female, female, fem~
## $ smoke  &lt;fct&gt; non-current smoker, non-current smoker, non-current smoker, non~</code></pre>
<pre class="r"><code>summary(FEV)</code></pre>
<pre><code>##        id             age              fev            height          sex     
##  Min.   :  201   Min.   : 3.000   Min.   :0.791   Min.   :46.00   female:318  
##  1st Qu.:15811   1st Qu.: 8.000   1st Qu.:1.981   1st Qu.:57.00   male  :336  
##  Median :36071   Median :10.000   Median :2.547   Median :61.50               
##  Mean   :37170   Mean   : 9.931   Mean   :2.637   Mean   :61.14               
##  3rd Qu.:53639   3rd Qu.:12.000   3rd Qu.:3.119   3rd Qu.:65.50               
##  Max.   :90001   Max.   :19.000   Max.   :5.793   Max.   :74.00               
##                 smoke    
##  non-current smoker:589  
##  current smoker    : 65  
##                          
##                          
##                          
## </code></pre>
<pre class="r"><code># Fit initial additive model
fev.lin &lt;- ols(fev ~ age + height + sex + smoke, data = FEV)
fev.lin</code></pre>
<pre><code>## Linear Regression Model
##  
##  ols(formula = fev ~ age + height + sex + smoke, data = FEV)
##  
##                  Model Likelihood    Discrimination    
##                        Ratio Test           Indexes    
##  Obs     654    LR chi2    976.59    R2       0.775    
##  sigma0.4122    d.f.            4    R2 adj   0.774    
##  d.f.    649    Pr(&gt; chi2) 0.0000    g        0.869    
##  
##  Residuals
##  
##        Min        1Q    Median        3Q       Max 
##  -1.376562 -0.250333  0.008938  0.255879  1.920471 
##  
##  
##                       Coef    S.E.   t      Pr(&gt;|t|)
##  Intercept            -4.4570 0.2228 -20.00 &lt;0.0001 
##  age                   0.0655 0.0095   6.90 &lt;0.0001 
##  height                0.1042 0.0048  21.90 &lt;0.0001 
##  sex=male              0.1571 0.0332   4.73 &lt;0.0001 
##  smoke=current smoker -0.0872 0.0593  -1.47 0.1414  
## </code></pre>
<pre class="r"><code>anova(fev.lin)</code></pre>
<pre><code>##                 Analysis of Variance          Response: fev 
## 
##  Factor     d.f. Partial SS  MS         F      P     
##  age          1    8.0994719  8.0994719  47.67 &lt;.0001
##  height       1   81.5049421 81.5049421 479.66 &lt;.0001
##  sex          1    3.8032782  3.8032782  22.38 &lt;.0001
##  smoke        1    0.3683978  0.3683978   2.17 0.1414
##  REGRESSION   4  380.6402823 95.1600706 560.02 &lt;.0001
##  ERROR      649  110.2795540  0.1699223</code></pre>
<ul>
<li><code>age</code> and <code>height</code> are continuous variables, so we can use residual plots.</li>
<li><code>sex</code> and <code>smoke</code> are categorical variables (in fact, they’re binary) so residual plots won’t be useful.</li>
</ul>
<pre class="r"><code>dx.fev &lt;- data.frame(FEV, e = resid(fev.lin), yhat = fitted(fev.lin))

xyplot(e ~ age, data = dx.fev, type = c(&quot;p&quot;, &quot;smooth&quot;))</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<pre class="r"><code>xyplot(e ~ height, data = dx.fev, type = c(&quot;p&quot;, &quot;smooth&quot;))</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-15-2.png" width="672" /></p>
<ul>
<li>The residual plots show that non-linearity needs to be modelled for both variables.</li>
<li>Once again, we shall use restricted cubic splines with 4 knots.</li>
</ul>
<pre class="r"><code>fev.full &lt;- ols(fev ~ rcs(age, 4) + rcs(height, 4) + sex + smoke, data = FEV)

fev.full</code></pre>
<pre><code>## Linear Regression Model
##  
##  ols(formula = fev ~ rcs(age, 4) + rcs(height, 4) + sex + smoke, 
##      data = FEV)
##  
##                   Model Likelihood    Discrimination    
##                         Ratio Test           Indexes    
##  Obs     654    LR chi2    1039.74    R2       0.796    
##  sigma0.3940    d.f.             8    R2 adj   0.794    
##  d.f.    645    Pr(&gt; chi2)  0.0000    g        0.878    
##  
##  Residuals
##  
##        Min        1Q    Median        3Q       Max 
##  -1.637487 -0.223633  0.008879  0.236143  1.776429 
##  
##  
##                       Coef    S.E.   t     Pr(&gt;|t|)
##  Intercept            -2.7618 0.6718 -4.11 &lt;0.0001 
##  age                  -0.0109 0.0343 -0.32 0.7509  
##  age&#39;                  0.1815 0.0733  2.48 0.0135  
##  age&#39;&#39;                -0.7112 0.3094 -2.30 0.0218  
##  height                0.0834 0.0151  5.51 &lt;0.0001 
##  height&#39;               0.0114 0.0308  0.37 0.7114  
##  height&#39;&#39;              0.1252 0.1349  0.93 0.3540  
##  sex=male              0.0951 0.0335  2.83 0.0047  
##  smoke=current smoker -0.1485 0.0576 -2.58 0.0102  
## </code></pre>
<pre class="r"><code>anova(fev.full)</code></pre>
<pre><code>##                 Analysis of Variance          Response: fev 
## 
##  Factor          d.f. Partial SS  MS         F      P     
##  age               3   10.2137671  3.4045890  21.93 &lt;.0001
##   Nonlinear        2    0.9847797  0.4923898   3.17 0.0426
##  height            3   80.2711567 26.7570522 172.36 &lt;.0001
##   Nonlinear        2    3.1249430  1.5624715  10.06 &lt;.0001
##  sex               1    1.2475614  1.2475614   8.04 0.0047
##  smoke             1    1.0306405  1.0306405   6.64 0.0102
##  TOTAL NONLINEAR   4   10.1495441  2.5373860  16.34 &lt;.0001
##  REGRESSION        8  390.7898263 48.8487283 314.67 &lt;.0001
##  ERROR           645  100.1300100  0.1552403</code></pre>
<ul>
<li>The <code>anova()</code> output suggests that the non-linear components for age and height are statistically significant.</li>
</ul>
<pre class="r"><code>dx.full &lt;- data.frame(FEV, e = resid(fev.full), yhat = fitted(fev.full))

# Residual plots look good
xyplot(e ~ age, data = dx.full, type = c(&quot;p&quot;, &quot;smooth&quot;))</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<pre class="r"><code>xyplot(e ~ height, data = dx.full, type = c(&quot;p&quot;, &quot;smooth&quot;))</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-18-2.png" width="672" /></p>
<ul>
<li>Running <code>summary()</code> is the best way to get the effects of the categorical variables.</li>
<li>For continuous variables, it is better to plot.</li>
</ul>
<pre class="r"><code>summary(fev.full)</code></pre>
<pre><code>##              Effects              Response : fev 
## 
##  Factor                                    Low High Diff. Effect    S.E.    
##  age                                        8  12.0 4.0    0.344100 0.059919
##  height                                    57  65.5 8.5    0.888570 0.061187
##  sex - female:male                          2   1.0  NA   -0.095061 0.033533
##  smoke - current smoker:non-current smoker  1   2.0  NA   -0.148540 0.057649
##  Lower 0.95 Upper 0.95
##   0.22644    0.461760 
##   0.76842    1.008700 
##  -0.16091   -0.029214 
##  -0.26174   -0.035337</code></pre>
<pre class="r"><code>ggplot(Predict(fev.full, age))</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<pre class="r"><code>ggplot(Predict(fev.full, height))</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-20-2.png" width="672" /></p>
</div>
<div id="extra" class="section level2">
<h2>Extra</h2>
<ul>
<li><code>%&gt;%</code>: pipe operator - very useful for performing multiple data wrangling steps</li>
<li><code>ggplot2()</code>: plotting package, included in <code>rms()</code> and <code>tidyverse()</code></li>
</ul>
<pre class="r"><code># Boxplot
FEV %&gt;%
  ggplot(mapping = aes(x = sex, y = height, fill = sex)) +
  geom_boxplot() +
  theme_bw() +
  labs(title = &quot;Boxplot of heights by sex&quot;)</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
</div>
</div>
<div id="tutorial-2" class="section level1">
<h1>Tutorial 2</h1>
<div id="question-1-1" class="section level2">
<h2>Question 1</h2>
<p>Use the hwy2.RData file available from the course page. After attaching the rms package and doing the usual <code>datadist()/options()</code> task, fit the following model:</p>
<p><code>fit &lt;- ols(rate~rcs(trks,4)+rcs(sigs1,4)+type+hwy,data=hwy2,x=TRUE,y=TRUE)</code></p>
<p>Run both the ordinary bootstrap validation and the .632 bootstrap validation on this model. Use the same number of iterations and seed for both validations (to compare the results). What are your conclusions?</p>
<pre class="r"><code>library(rms)

load(&quot;./CHL5202/hwy2.RData&quot;)

h.dd &lt;- datadist(hwy2)
options(datadist=&quot;h.dd&quot;)

fit &lt;- ols(rate ~ rcs(trks,4) + rcs(sigs1,4) + type + hwy, data=hwy2, x=TRUE, y=TRUE)</code></pre>
<pre class="r"><code># Standard bootstrap
set.seed(321) # Set seed is reproducibility. Choose any number you like.
validate(fit, B=100)</code></pre>
<pre><code>## 
## Divergence or singularity in 11 samples</code></pre>
<pre><code>##           index.orig training   test optimism index.corrected  n
## R-square      0.7110   0.7802 0.3163   0.4640          0.2471 89
## MSE           1.1106   0.7859 2.6277  -1.8418          2.9523 89
## g             1.8604   1.8808 1.6933   0.1876          1.6728 89
## Intercept     0.0000   0.0000 0.6535  -0.6535          0.6535 89
## Slope         1.0000   1.0000 0.8493   0.1507          0.8493 89</code></pre>
<pre class="r"><code># .632 bootstrap
set.seed(321)
validate(fit, method = &quot;.632&quot;, B=100)</code></pre>
<pre><code>## 
## Divergence or singularity in 11 samples</code></pre>
<pre><code>##           index.orig training    test optimism index.corrected  n
## R-square      0.7110   0.7802 -0.3786   0.6886          0.0224 89
## MSE           1.1106   0.7859  5.0256  -2.4743          3.5849 89
## g             1.8604   1.8808  1.2664   0.3754          1.4850 89
## Intercept     0.0000   0.0000  1.2077  -0.7633          0.7633 89
## Slope         1.0000   1.0000  0.5981   0.2540          0.7460 89</code></pre>
<p>Conclusions:</p>
<ul>
<li><p>There is a discrepancy in standard bootstrap vs .632 method – the standard bootstrap may be overfitting so we use the .632 method to double check the validation results. The .632 bootstrap applies a correction factor to reduce the bias.</p></li>
<li><p>Standard bootstrap may believe the model is less overfit than what it actually is, i.e. low optimism so <code>index.corrected</code> is closer to <code>index.orig</code>.</p></li>
<li><p>The drop in R-square is very large from validation (went from positive to negative), indicating the original model was very overfit to the point where the relationship inverted.</p></li>
<li><p>Slope change seems to imply an adjusted slope estimate should be around 0.75 of what the original model guessed.</p></li>
</ul>
</div>
<div id="extra-1" class="section level2">
<h2>Extra</h2>
<p>Let’s investigate the outputs from a simpler model.</p>
<pre class="r"><code># We remove the restricted cubic splines which may be the main source of overfitting
fit2 &lt;- ols(rate ~ trks + sigs1 + type + hwy, data=hwy2, x=TRUE, y=TRUE)

set.seed(321)
validate(fit2, B=100)</code></pre>
<pre><code>## 
## Divergence or singularity in 11 samples</code></pre>
<pre><code>##           index.orig training   test optimism index.corrected  n
## R-square      0.6031   0.6535 0.5132   0.1402          0.4628 89
## MSE           1.5255   1.2468 1.8708  -0.6240          2.1494 89
## g             1.6155   1.6571 1.5645   0.0926          1.5230 89
## Intercept     0.0000   0.0000 0.3534  -0.3534          0.3534 89
## Slope         1.0000   1.0000 0.9146   0.0854          0.9146 89</code></pre>
<pre class="r"><code>set.seed(321)
validate(fit2, method = &quot;.632&quot;, B=100)</code></pre>
<pre><code>## 
## Divergence or singularity in 11 samples</code></pre>
<pre><code>##           index.orig training   test optimism index.corrected  n
## R-square      0.6031   0.6535 0.1379   0.2940          0.3091 89
## MSE           1.5255   1.2468 2.4057  -0.5563          2.0818 89
## g             1.6155   1.6571 1.2776   0.2136          1.4019 89
## Intercept     0.0000   0.0000 0.5816  -0.3676          0.3676 89
## Slope         1.0000   1.0000 0.7459   0.1606          0.8394 89</code></pre>
<ul>
<li><p>For the .632 bootstrap, the magnitude of the optimism for all 5 values is smaller than in the saturated model which showed overfitting.</p></li>
<li><p>Hard to say whether this model is still overfitting but it is certainly an improvement.</p></li>
<li><p>The R-square term in particular shows a major improvement, as the test R-square is positive rather than negative like previously shown.</p></li>
</ul>
</div>
</div>
<div id="tutorial-3" class="section level1">
<h1>Tutorial 3</h1>
<div id="question-1-2" class="section level2">
<h2>Question 1</h2>
<p>Load the data from <code>tutdata</code> from the file <code>tutdata.RData</code> posted on the course page. Fit an additive model where <code>y</code> is the outcome and the predictors are <code>blood.pressure</code>, <code>sex</code>, <code>age</code>, and <code>cholesterol</code> but they should use a restricted cubic spline with four knots for cholesterol.</p>
<pre class="r"><code>library(rms)
load(&quot;./CHL5202/tutdata.RData&quot;)

dd &lt;- datadist(tutdata)
options(datadist=&quot;dd&quot;)

fit &lt;- lrm(y ~ blood.pressure + sex + age + rcs(cholesterol,4), data = tutdata)</code></pre>
</div>
<div id="question-2-1" class="section level2">
<h2>Question 2</h2>
<p>Which “variables” are significant at the 5% level?</p>
<pre class="r"><code>anova(fit)</code></pre>
<pre><code>##                 Wald Statistics          Response: y 
## 
##  Factor         Chi-Square d.f. P     
##  blood.pressure  0.33      1    0.5640
##  sex            13.45      1    0.0002
##  age            25.58      1    &lt;.0001
##  cholesterol     1.27      3    0.7368
##   Nonlinear      0.78      2    0.6758
##  TOTAL          38.63      6    &lt;.0001</code></pre>
<ul>
<li>At the 5% significance level, <code>sex</code> and <code>age</code> are statistically significant with p-values of 0.0002 and &lt; 0.0001 respectively.</li>
</ul>
</div>
<div id="question-3" class="section level2">
<h2>Question 3</h2>
<p>Display the cholesterol effect.</p>
<pre class="r"><code># log odds
plot(Predict(fit,cholesterol))</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<pre class="r"><code># probability
plot(Predict(fit,cholesterol,fun=plogis), ylab=&quot;Probability&quot;)</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-27-2.png" width="672" /></p>
<pre class="r"><code># odds
plot(Predict(fit,cholesterol,fun=exp), ylab=&quot;Odds&quot;)</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-27-3.png" width="672" /></p>
</div>
<div id="question-4" class="section level2">
<h2>Question 4</h2>
<p>Describe the effect of sex.</p>
<pre class="r"><code>summary(fit)</code></pre>
<pre><code>##              Effects              Response : y 
## 
##  Factor            Low     High    Diff.  Effect    S.E.     Lower 0.95
##  blood.pressure    109.580 130.580 20.991 -0.052121 0.090347 -0.22920  
##   Odds Ratio       109.580 130.580 20.991  0.949210       NA  0.79517  
##  age                43.531  56.677 13.146  0.438050 0.086609  0.26830  
##   Odds Ratio        43.531  56.677 13.146  1.549700       NA  1.30770  
##  cholesterol       183.730 216.530 32.796  0.194330 0.174400 -0.14748  
##   Odds Ratio       183.730 216.530 32.796  1.214500       NA  0.86288  
##  sex - male:female   1.000   2.000     NA  0.477030 0.130050  0.22213  
##   Odds Ratio         1.000   2.000     NA  1.611300       NA  1.24870  
##  Upper 0.95
##  0.12496   
##  1.13310   
##  0.60780   
##  1.83640   
##  0.53615   
##  1.70940   
##  0.73192   
##  2.07910</code></pre>
<ul>
<li>The odds of the outcome <code>y</code> for males is 1.61 times the odds for females (with 95% CI [1.25,2.08]) controlled for blood pressure, age and cholesterol.</li>
</ul>
</div>
<div id="extra-2" class="section level2">
<h2>Extra</h2>
<ul>
<li>Interpreting odds ratios for continuous variables: for every one unit increase in the continuous variable, the odds of the outcome multiply by <span class="math inline">\(\exp(\beta)\)</span>, where <span class="math inline">\(\beta\)</span> represents the log-odds ratio.</li>
<li>E.g. referring to Question 4 output: for every one year increase in age, the odds of the outcome multiply by 1.55. Alternatively, it might be more intuitive to say that the odds of the outcome increases by 55%.</li>
</ul>
</div>
</div>
<div id="tutorial-4" class="section level1">
<h1>Tutorial 4</h1>
<div id="question-1-3" class="section level2">
<h2>Question 1</h2>
<p>Use the data from last week (<code>tutdata.RData</code>) and re-fit the model from last week which was an additive model where <code>y</code> is the outcome and the predictors are <code>blood.pressure</code>, <code>sex</code>, <code>age</code>, and <code>cholesterol</code> except this time use a restricted cubic spline with four knots for <code>cholesterol</code>. Re-run the anova also.</p>
<pre class="r"><code>library(rms)
load(&quot;./CHL5202/tutdata.RData&quot;)

dd &lt;- datadist(tutdata)
options(datadist=&quot;dd&quot;)

fit1 &lt;- lrm(y ~ blood.pressure + sex + age + rcs(cholesterol,4), data = tutdata)
anova(fit1)</code></pre>
<pre><code>##                 Wald Statistics          Response: y 
## 
##  Factor         Chi-Square d.f. P     
##  blood.pressure  0.33      1    0.5640
##  sex            13.45      1    0.0002
##  age            25.58      1    &lt;.0001
##  cholesterol     1.27      3    0.7368
##   Nonlinear      0.78      2    0.6758
##  TOTAL          38.63      6    &lt;.0001</code></pre>
</div>
<div id="question-2-2" class="section level2">
<h2>Question 2</h2>
<p>Fit a model as above only this time, add interactions between sex and age as well as sex and the RCS for cholesterol and run anova() on this model.</p>
<pre class="r"><code>fit2 &lt;- lrm(y ~ blood.pressure + sex * (age + rcs(cholesterol,4)), data = tutdata)
anova(fit2)</code></pre>
<pre><code>##                 Wald Statistics          Response: y 
## 
##  Factor                                           Chi-Square d.f. P     
##  blood.pressure                                    0.26       1   0.6105
##  sex  (Factor+Higher Order Factors)               38.71       5   &lt;.0001
##   All Interactions                                26.13       4   &lt;.0001
##  age  (Factor+Higher Order Factors)               30.42       2   &lt;.0001
##   All Interactions                                 3.86       1   0.0495
##  cholesterol  (Factor+Higher Order Factors)       23.78       6   0.0006
##   All Interactions                                22.47       3   0.0001
##   Nonlinear (Factor+Higher Order Factors)          5.33       4   0.2550
##  sex * age  (Factor+Higher Order Factors)          3.86       1   0.0495
##  sex * cholesterol  (Factor+Higher Order Factors) 22.47       3   0.0001
##   Nonlinear                                        4.79       2   0.0911
##   Nonlinear Interaction : f(A,B) vs. AB            4.79       2   0.0911
##  TOTAL NONLINEAR                                   5.33       4   0.2550
##  TOTAL INTERACTION                                26.13       4   &lt;.0001
##  TOTAL NONLINEAR + INTERACTION                    26.81       6   0.0002
##  TOTAL                                            62.26      10   &lt;.0001</code></pre>
<ul>
<li>All interactions with sex are statistically significant.</li>
</ul>
</div>
<div id="question-3-1" class="section level2">
<h2>Question 3</h2>
<p>Compare the two models with a likelihood ratio test. What does it show?</p>
<pre class="r"><code>lrtest(fit1,fit2)</code></pre>
<pre><code>## 
## Model 1: y ~ blood.pressure + sex + age + rcs(cholesterol, 4)
## Model 2: y ~ blood.pressure + sex * (age + rcs(cholesterol, 4))
## 
##   L.R. Chisq         d.f.            P 
## 2.831616e+01 4.000000e+00 1.076137e-05</code></pre>
<ul>
<li>We are testing the null hypothesis that all of the coefficients for the interaction terms are equal to 0.</li>
<li>Degrees of freedom (df): 10 df (more complicated model) minus 6 df (simpler model) equals 4 df.</li>
<li>With the extremely small p-value from the likelihood ratio test, we reject the null hypothesis and conclude that at least one of the coefficients is not equal to 0.</li>
<li>This p-value is equivalent to the p-value for <code>TOTAL INTERACTION</code> in the <code>anova(fit2)</code> output as this is what we are testing.</li>
</ul>
</div>
<div id="question-4-1" class="section level2">
<h2>Question 4</h2>
<p>Describe the sex/age and sex/cholesterol relationships with outcome.</p>
<pre class="r"><code>plot(Predict(fit2,age,sex))</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<pre class="r"><code>plot(Predict(fit2,cholesterol,sex))</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-32-2.png" width="672" /></p>
<ul>
<li>We can use the non-overlapping confidence intervals to specify statistical significance. If this is too complicated we can also discuss the points where the lines cross. This is an open ended question.</li>
<li>At ages below 50, the log odds of the outcome is statistically significantly higher for males compared to females. From ages 50 to 70, the log odds is still higher for males but the confidence intervals overlap so the difference is not as significant.</li>
<li>For cholesterol levels below 150, the log odds of the outcome is statistically significantly higher for females compared to males. The opposite is true in cholesterol levels from 190 to 200, and above 220. There is a bit of overlap in confidence intervals between the 200-220 range.</li>
</ul>
<pre class="r"><code># Fancy way of combining the plots together but is harder to interpret
bplot(Predict(fit2,cholesterol,age,sex,np=20),lfun=wireframe,drape=TRUE)</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
</div>
<div id="extra-3" class="section level2">
<h2>Extra</h2>
<ul>
<li>Below we are fitting a third model with an interaction term between sex and the other 3 variables, including blood pressure.</li>
</ul>
<pre class="r"><code>fit3 &lt;- lrm(y ~ sex * (blood.pressure + age + rcs(cholesterol,4)), data = tutdata)
# Alternate way
#lrm(y ~ sex + blood.pressure + age + rcs(cholesterol,4) + sex:blood.pressure + sex:age + sex:rcs(cholesterol,4), data = tutdata)

anova(fit3)</code></pre>
<pre><code>##                 Wald Statistics          Response: y 
## 
##  Factor                                              Chi-Square d.f. P     
##  sex  (Factor+Higher Order Factors)                  39.12       6   &lt;.0001
##   All Interactions                                   26.58       5   0.0001
##  blood.pressure  (Factor+Higher Order Factors)        0.73       2   0.6954
##   All Interactions                                    0.47       1   0.4940
##  age  (Factor+Higher Order Factors)                  30.58       2   &lt;.0001
##   All Interactions                                    3.94       1   0.0471
##  cholesterol  (Factor+Higher Order Factors)          23.96       6   0.0005
##   All Interactions                                   22.59       3   &lt;.0001
##   Nonlinear (Factor+Higher Order Factors)             5.24       4   0.2634
##  sex * blood.pressure  (Factor+Higher Order Factors)  0.47       1   0.4940
##  sex * age  (Factor+Higher Order Factors)             3.94       1   0.0471
##  sex * cholesterol  (Factor+Higher Order Factors)    22.59       3   &lt;.0001
##   Nonlinear                                           4.67       2   0.0966
##   Nonlinear Interaction : f(A,B) vs. AB               4.67       2   0.0966
##  TOTAL NONLINEAR                                      5.24       4   0.2634
##  TOTAL INTERACTION                                   26.58       5   0.0001
##  TOTAL NONLINEAR + INTERACTION                       27.25       7   0.0003
##  TOTAL                                               62.64      11   &lt;.0001</code></pre>
<ul>
<li>The total interaction from the anova output is still statistically significant as it takes into account all interactions.</li>
<li>We can also test for it below as follows:</li>
</ul>
<pre class="r"><code>lrtest(fit1,fit3)</code></pre>
<pre><code>## 
## Model 1: y ~ blood.pressure + sex + age + rcs(cholesterol, 4)
## Model 2: y ~ sex * (blood.pressure + age + rcs(cholesterol, 4))
## 
##   L.R. Chisq         d.f.            P 
## 2.878410e+01 5.000000e+00 2.556193e-05</code></pre>
<ul>
<li>The sex and blood pressure interaction term from the anova output is not significant (p=0.494).</li>
<li>This is equivalent to the p-value from the likelihood ratio test below:</li>
</ul>
<pre class="r"><code>lrtest(fit2,fit3)</code></pre>
<pre><code>## 
## Model 1: y ~ blood.pressure + sex * (age + rcs(cholesterol, 4))
## Model 2: y ~ sex * (blood.pressure + age + rcs(cholesterol, 4))
## 
## L.R. Chisq       d.f.          P 
##  0.4679391  1.0000000  0.4939368</code></pre>
<ul>
<li>Let’s try to plot the sex/blood pressure relationship:</li>
</ul>
<pre class="r"><code>plot(Predict(fit3,blood.pressure,sex))</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<ul>
<li>At a first glance we do not see the lines meet like they do in the sex/age and sex/cholesterol interactions. The confidence intervals also overlap for the most part, except in the 115-130 range.</li>
<li>Personally, I would avoid using this as a standalone method to check for a significant interaction, you should use either the anova function call or the likelihood ratio test.</li>
</ul>
</div>
</div>
<div id="tutorial-5" class="section level1">
<h1>Tutorial 5</h1>
<div id="question-1-4" class="section level2">
<h2>Question 1</h2>
<p>Using the data from the last few tutorials, fit the following model.</p>
<p><code>fit &lt;- lrm(y ~ blood.pressure + sex * (age + rcs(cholesterol,4)), data = tutdata, x=TRUE, y=TRUE)</code></p>
<pre class="r"><code>library(rms)
load(&quot;./CHL5202/tutdata.RData&quot;)

dd &lt;- datadist(tutdata)
options(datadist = &quot;dd&quot;)</code></pre>
<pre class="r"><code>fit &lt;- lrm(y ~ blood.pressure + sex * (age + rcs(cholesterol, 4)), data = tutdata, 
           x = TRUE, y = TRUE)
fit</code></pre>
<pre><code>## Logistic Regression Model
##  
##  lrm(formula = y ~ blood.pressure + sex * (age + rcs(cholesterol, 
##      4)), data = tutdata, x = TRUE, y = TRUE)
##  
##                         Model Likelihood    Discrimination    Rank Discrim.    
##                               Ratio Test           Indexes          Indexes    
##  Obs          1000    LR chi2      69.39    R2       0.090    C       0.642    
##   0            460    d.f.            10    g        0.623    Dxy     0.283    
##   1            540    Pr(&gt; chi2) &lt;0.0001    gr       1.865    gamma   0.283    
##  max |deriv| 1e-08                          gp       0.146    tau-a   0.141    
##                                             Brier    0.232                     
##  
##                           Coef    S.E.   Wald Z Pr(&gt;|Z|)
##  Intercept                 3.2474 2.3426  1.39  0.1657  
##  blood.pressure           -0.0022 0.0044 -0.51  0.6105  
##  sex=male                 -9.3612 3.5422 -2.64  0.0082  
##  age                       0.0474 0.0094  5.06  &lt;0.0001 
##  cholesterol              -0.0308 0.0133 -2.31  0.0209  
##  cholesterol&#39;              0.0738 0.0376  1.96  0.0499  
##  cholesterol&#39;&#39;            -0.3072 0.1552 -1.98  0.0477  
##  sex=male * age           -0.0263 0.0134 -1.96  0.0495  
##  sex=male * cholesterol    0.0620 0.0203  3.06  0.0022  
##  sex=male * cholesterol&#39;  -0.1241 0.0569 -2.18  0.0293  
##  sex=male * cholesterol&#39;&#39;  0.5116 0.2362  2.17  0.0303  
## </code></pre>
</div>
<div id="question-2-3" class="section level2">
<h2>Question 2</h2>
<p>Validate the model using the bootstrap with 100 replications and comment on the overfitting.</p>
<pre class="r"><code>set.seed(123)
validate(fit, B = 100)</code></pre>
<pre><code>##           index.orig training   test optimism index.corrected   n
## Dxy           0.2832   0.3025 0.2685   0.0340          0.2493 100
## R2            0.0896   0.1024 0.0792   0.0232          0.0664 100
## Intercept     0.0000   0.0000 0.0108  -0.0108          0.0108 100
## Slope         1.0000   1.0000 0.8768   0.1232          0.8768 100
## Emax          0.0000   0.0000 0.0311   0.0311          0.0311 100
## D             0.0684   0.0788 0.0601   0.0187          0.0496 100
## U            -0.0020  -0.0020 0.0013  -0.0033          0.0013 100
## Q             0.0704   0.0808 0.0588   0.0220          0.0484 100
## B             0.2316   0.2289 0.2341  -0.0052          0.2367 100
## g             0.6230   0.6708 0.5787   0.0921          0.5309 100
## gp            0.1457   0.1541 0.1358   0.0183          0.1273 100</code></pre>
<ul>
<li>There is mild evidence of overfitting.</li>
<li><span class="math inline">\(D_{xy}\)</span> and Brier score (<code>B</code>) do not change much at all.</li>
<li>Slope parameter indicates a need to shrink by about 12% to calibrate</li>
</ul>
</div>
<div id="question-3-2" class="section level2">
<h2>Question 3</h2>
<p>Investigate influential observations and partial residual plots.</p>
<pre class="r"><code>dff &lt;- resid(fit, &quot;dffits&quot;)
plot(dff)</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<ul>
<li>The DFFITS statistic indicate the effect that deleting each observation has on the predicted values of the model.</li>
<li>Some use <span class="math inline">\(|\text{DFFITS}| &gt; 2\sqrt{\frac{p+1}{n-p-1}}\)</span> to indicate an influential observation.</li>
</ul>
<pre class="r"><code>show.influence(which.influence(fit), data.frame(tutdata, dffits = dff), report = c(&quot;dffits&quot;))</code></pre>
<pre><code>##     Count     sex cholesterol     dffits
## 143     2  female   *274.0808  1.6108318
## 173     4 *female   *138.5056 -1.1265158
## 181     2 *male      146.4978  0.8026558
## 408     2 *male      148.1649  0.6813596
## 411     1  female    146.3522  0.5594519
## 834     2  female   *146.6413 -0.4908278
## 840     2  female   *147.0025 -0.5604495</code></pre>
<ul>
<li>Using <code>which.influence()</code> gives the indices of influential observations, which are listed in the first column of the dataframe above.</li>
<li>The variables with significant DFBETA are marked with an asterisk. Note that all of these observations have significant DFFITS.</li>
<li>The DFBETAS are statistics that indicate the effect that deleting each observation has on the estimates for the regression coefficients.</li>
<li>For DFBETAS one can use <span class="math inline">\(|\text{DFBETAS}| &gt; u\)</span> for a given cutoff, the default is 0.2.</li>
</ul>
<p>Below we investigate partial residual plots which can be used to verify the functional form of continuous covariates.</p>
<pre class="r"><code># Option below saves the following plots to a pdf file
# pdf(&quot;resid_plots.pdf&quot;)

resid(fit, &quot;partial&quot;, pl = &quot;loess&quot;)</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-43-1.png" width="672" /><img src="CHL5202_files/figure-html/unnamed-chunk-43-2.png" width="672" /><img src="CHL5202_files/figure-html/unnamed-chunk-43-3.png" width="672" /><img src="CHL5202_files/figure-html/unnamed-chunk-43-4.png" width="672" /><img src="CHL5202_files/figure-html/unnamed-chunk-43-5.png" width="672" /><img src="CHL5202_files/figure-html/unnamed-chunk-43-6.png" width="672" /><img src="CHL5202_files/figure-html/unnamed-chunk-43-7.png" width="672" /><img src="CHL5202_files/figure-html/unnamed-chunk-43-8.png" width="672" /><img src="CHL5202_files/figure-html/unnamed-chunk-43-9.png" width="672" /><img src="CHL5202_files/figure-html/unnamed-chunk-43-10.png" width="672" /></p>
<ul>
<li>There is very little evidence of non-linearity in most of these plots, i.e. there is not much value in including a non-linear component for these variables.</li>
</ul>
</div>
</div>
<div id="tutorial-6" class="section level1">
<h1>Tutorial 6</h1>
<p>Over the next few weeks the tutorials will use the data frame <code>mgus2</code> which may be found in the survival package. Since the survival package is attached when <code>rms</code> is, nothing special is required to access it, other than loading the <code>rms</code> package.</p>
<pre class="r"><code>library(rms)

str(mgus2)</code></pre>
<pre><code>## &#39;data.frame&#39;:    1384 obs. of  11 variables:
##  $ id    : num  1 2 3 4 5 6 7 8 9 10 ...
##  $ age   : num  88 78 94 68 90 90 89 87 86 79 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;AGE AT mgus_sp&quot;
##  $ sex   : Factor w/ 2 levels &quot;F&quot;,&quot;M&quot;: 1 1 2 2 1 2 1 1 1 1 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Sex&quot;
##   ..- attr(*, &quot;format&quot;)= chr &quot;$desex&quot;
##  $ dxyr  : num  1981 1968 1980 1977 1973 ...
##  $ hgb   : num  13.1 11.5 10.5 15.2 10.7 12.9 10.5 12.3 14.5 9.4 ...
##  $ creat : num  1.3 1.2 1.5 1.2 0.8 1 0.9 1.2 0.9 1.1 ...
##  $ mspike: num  0.5 2 2.6 1.2 1 0.5 1.3 1.6 2.4 2.3 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;SEP SPIKE AT mgus_sp&quot;
##  $ ptime : num  30 25 46 92 8 4 151 2 57 136 ...
##  $ pstat : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ futime: num  30 25 46 92 8 4 151 2 57 136 ...
##  $ death : num  1 1 1 1 1 1 1 1 0 1 ...</code></pre>
<p>More information about the data can be found in the help file (e.g. <code>?mgus2</code>).</p>
<div id="question-1-5" class="section level2">
<h2>Question 1</h2>
<p>Estimate the Kaplan-Meier curves for survival for males and females and plot the result.</p>
<pre class="r"><code># The rms package has a function npsurv which is used in place of the usual survfit.
fit &lt;- npsurv(Surv(futime, death) ~ sex, data = mgus2)

# Two methods below:
plot(fit, lty = c(1, 2)) # standard method</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<pre class="r"><code>survplot(fit, n.risk = TRUE) #a more flexible function from rms</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-45-2.png" width="672" /></p>
</div>
<div id="question-2-4" class="section level2">
<h2>Question 2</h2>
<p>Test <span class="math inline">\(H_0 : S_F(t) = S_M(t)\)</span> versus <span class="math inline">\(H_0 : S_F(t) \neq S_M(t).\)</span></p>
<pre class="r"><code># This requires the Mantel-Haenzel (log-rank) test.
print(fit.mh &lt;- survdiff(Surv(futime, death) ~ sex, data = mgus2))</code></pre>
<pre><code>## Call:
## survdiff(formula = Surv(futime, death) ~ sex, data = mgus2)
## 
##         N Observed Expected (O-E)^2/E (O-E)^2/V
## sex=F 631      423      471      4.88      9.67
## sex=M 753      540      492      4.67      9.67
## 
##  Chisq= 9.7  on 1 degrees of freedom, p= 0.002</code></pre>
<ul>
<li>The Mantel-Haenzel test yields a p-value of 0.002, so we reject the null hypothesis as there is strong evidence that the survival function for females is not equal to the survival function for males.</li>
</ul>
</div>
<div id="question-3-3" class="section level2">
<h2>Question 3</h2>
<p>Compute the risk difference at one year.</p>
<pre class="r"><code>(summ &lt;- summary(fit, times = 12)) # time is in months</code></pre>
<pre><code>## Call: npsurv(formula = Surv(futime, death) ~ sex, data = mgus2)
## 
##                 sex=F 
##         time       n.risk      n.event     survival      std.err lower 95% CI 
##      12.0000     569.0000      61.0000       0.9032       0.0118       0.8804 
## upper 95% CI 
##       0.9266 
## 
##                 sex=M 
##         time       n.risk      n.event     survival      std.err lower 95% CI 
##       12.000      646.000      112.000        0.851        0.013        0.826 
## upper 95% CI 
##        0.877</code></pre>
<ul>
<li>The risk difference (assigning females as control and males as treatment) is:</li>
</ul>
<p><span class="math display">\[ 
\begin{aligned}
\widehat{RD} &amp;= \hat{F}_C(t_0)-\hat{F}_T(t_0) \\
&amp;= (1-\hat{S}_C(t_0))(1-\hat{S}_T(t_0)) \\
&amp;= \hat{S}_T(t_0)-\hat{S}_C(t_0) \\
&amp;= 0.851 - 0.9032 \\
&amp;= -0.0522
\end{aligned}
\]</span></p>
<ul>
<li>Using R:</li>
</ul>
<pre class="r"><code>(rd &lt;- summ$surv[2] - summ$surv[1])</code></pre>
<pre><code>## [1] -0.05194881</code></pre>
<pre class="r"><code>fit$surv[length(fit$surv)-232+12] - fit$surv[12] # alternative</code></pre>
<pre><code>## [1] -0.05194881</code></pre>
<ul>
<li><p>Interpretation: The observed risk of death in females at one year is 5.2% lower than in males.</p></li>
<li><p>(Extra) A 95% confidence interval for the risk difference is:</p></li>
</ul>
<p><span class="math display">\[
\begin{aligned}
&amp;\widehat{RD} \pm 1.96\sqrt{\hat{V}[\hat{S}_C(t_0)] + \hat{V}[\hat{S}_T(t_0)]} \\
&amp;= -0.0522 \pm 1.96\sqrt{0.0118^2 + 0.013^2} \\
&amp;= (-0.0866,-0.0178)
\end{aligned}
\]</span></p>
<ul>
<li>Using R:</li>
</ul>
<pre class="r"><code>bound &lt;- 1.96*sqrt(summ$std.err[1]^2 + summ$std.err[2]^2)

c(rd-bound, rd+bound)</code></pre>
<pre><code>## [1] -0.08628336 -0.01761427</code></pre>
</div>
<div id="question-4-2" class="section level2">
<h2>Question 4</h2>
<p>Compute a hazard ratio using the output from <code>survdiff</code>.</p>
<p><span class="math display">\[ 
\widehat{HR} = \frac{O_T/E_T}{O_C/E_C} = \frac{540/492}{423/471} = 1.222
\]</span></p>
<ul>
<li>Alternatively, we can calculate using <code>fit.mh</code>:</li>
</ul>
<pre class="r"><code># We can extract the numbers from fit.mh 
fit.mh$obs</code></pre>
<pre><code>## [1] 423 540</code></pre>
<pre class="r"><code>fit.mh$exp</code></pre>
<pre><code>## [1] 470.9283 492.0717</code></pre>
<pre class="r"><code># Observed / Expected 
female &lt;- fit.mh$obs[1]/fit.mh$exp[1] # 423/471
male &lt;- fit.mh$obs[2]/fit.mh$exp[2] # 540/492

# Hazard Ratio Using females as reference
hr &lt;- male/female # (540/492)/(423/471)
hr</code></pre>
<pre><code>## [1] 1.221743</code></pre>
<ul>
<li><p>The hazard ratio of 1.222 means that the rate of death for males is 1.222 times the rate of death for females.</p></li>
<li><p>(Extra) Obtaining a 95% CI for the hazard ratio, we start with the standard error:</p></li>
</ul>
<p><span class="math display">\[
SE[\log\widehat{HR}] = \sqrt{\frac{1}{E_T} + \frac{1}{E_C}} = \sqrt{\frac{1}{492} + \frac{1}{471}} = 0.06446
\]</span></p>
<ul>
<li>Which gives a 95% CI of:</li>
</ul>
<p><span class="math display">\[
1.222 \times e^{\pm1.96\times0.06446} = (1.0769,1.3866)
\]</span></p>
<ul>
<li>Using R:</li>
</ul>
<pre class="r"><code># Standard error of log hazard ratio
se &lt;- sqrt((1/fit.mh$exp[2]) + (1/fit.mh$exp[1]))

# 95% Confidence interval
c(1.222*exp(-1.96*se), 1.222*exp(+1.96*se))</code></pre>
<pre><code>## [1] 1.076956 1.386579</code></pre>
</div>
</div>
<div id="tutorial-7" class="section level1">
<h1>Tutorial 7</h1>
<p>You will again use the data frame mgus2 from the <code>rms</code> package.</p>
<pre class="r"><code>library(rms)

str(mgus2)</code></pre>
<pre><code>## &#39;data.frame&#39;:    1384 obs. of  11 variables:
##  $ id    : num  1 2 3 4 5 6 7 8 9 10 ...
##  $ age   : num  88 78 94 68 90 90 89 87 86 79 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;AGE AT mgus_sp&quot;
##  $ sex   : Factor w/ 2 levels &quot;F&quot;,&quot;M&quot;: 1 1 2 2 1 2 1 1 1 1 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Sex&quot;
##   ..- attr(*, &quot;format&quot;)= chr &quot;$desex&quot;
##  $ dxyr  : num  1981 1968 1980 1977 1973 ...
##  $ hgb   : num  13.1 11.5 10.5 15.2 10.7 12.9 10.5 12.3 14.5 9.4 ...
##  $ creat : num  1.3 1.2 1.5 1.2 0.8 1 0.9 1.2 0.9 1.1 ...
##  $ mspike: num  0.5 2 2.6 1.2 1 0.5 1.3 1.6 2.4 2.3 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;SEP SPIKE AT mgus_sp&quot;
##  $ ptime : num  30 25 46 92 8 4 151 2 57 136 ...
##  $ pstat : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ futime: num  30 25 46 92 8 4 151 2 57 136 ...
##  $ death : num  1 1 1 1 1 1 1 1 0 1 ...</code></pre>
<pre class="r"><code>dd &lt;- datadist(mgus2)
options(datadist = &quot;dd&quot;)</code></pre>
<div id="question-1-6" class="section level2">
<h2>Question 1</h2>
<p>Investigate if either the exponential or Weibull models would be appropriate to model the dependency of survival on sex.</p>
<pre class="r"><code>fit.km &lt;- npsurv(Surv(futime, death) ~ sex, data = mgus2)

# Check exponential
plot(fit.km, fun = &quot;cumhaz&quot;)</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
<pre class="r"><code># Check Weibull
plot(fit.km, fun = &quot;cloglog&quot;)</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-54-2.png" width="672" /></p>
<ul>
<li>The plots indicate that both models could be a good fit (as they are linear).</li>
</ul>
</div>
<div id="question-2-5" class="section level2">
<h2>Question 2</h2>
<p>Fit and interpret an exponential model and plot the result.</p>
<pre class="r"><code>print(fit1 &lt;- psm(Surv(futime,death)~sex,data=mgus2,dist=&quot;exponential&quot;))</code></pre>
<pre><code>## Parametric Survival Model: Exponential Distribution
##  
##  psm(formula = Surv(futime, death) ~ sex, data = mgus2, dist = &quot;exponential&quot;)
##  
##                 Model Likelihood    Discrimination    
##                       Ratio Test           Indexes    
##  Obs   1384    LR chi2      9.99    R2       0.007    
##  Events 963    d.f.            1    Dxy      0.062    
##  sigma    1    Pr(&gt; chi2) 0.0016    g        0.102    
##                                     gr       1.107    
##  
##              Coef    S.E.   Wald Z Pr(&gt;|Z|)
##  (Intercept)  5.0344 0.0486 103.54 &lt;0.0001 
##  sex=M       -0.2045 0.0649  -3.15 0.0016  
## </code></pre>
<ul>
<li>P-value of 0.0016 provides strong evidence that the rate of death is higher in males than females.</li>
</ul>
<pre class="r"><code># HR for sex: M vs. F
exp(-coef(fit1)[2])</code></pre>
<pre><code>##    sex=M 
## 1.226934</code></pre>
<ul>
<li>The hazard ratio of 1.227 means that the rate of death for males is 1.227 times the rate of death for females.</li>
</ul>
<pre class="r"><code># Survival time ratio
summary(fit1,sex=&quot;F&quot;)</code></pre>
<pre><code>##              Effects              Response : Surv(futime, death) 
## 
##  Factor               Low High Diff. Effect   S.E.    Lower 0.95 Upper 0.95
##  sex - M:F            1   2    NA    -0.20452 0.06493 -0.33189   -0.077146 
##   Survival Time Ratio 1   2    NA     0.81504      NA  0.71757    0.925750</code></pre>
<ul>
<li>The survival time ratio of 0.815 means that the median survival time for males is 0.815 times the median survival time for females.</li>
<li>The results can be interpreted in terms of any percentile survival time, but median is most common.</li>
<li>For the exponential model, the survival time ratio is the inverse of the hazard ratio. This is not the case for other models.</li>
</ul>
<pre class="r"><code>survplot(fit1,sex)
survplot(fit.km,add=TRUE,label.curves=FALSE,conf=&quot;none&quot;,col=&quot;red&quot;)</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
</div>
<div id="question-3-4" class="section level2">
<h2>Question 3</h2>
<p>Fit and interpret a Weibull model and plot the result.</p>
<pre class="r"><code>print(fit2 &lt;- psm(Surv(futime,death)~sex,data=mgus2,dist=&quot;weibull&quot;))</code></pre>
<pre><code>## Parametric Survival Model: Weibull Distribution
##  
##  psm(formula = Surv(futime, death) ~ sex, data = mgus2, dist = &quot;weibull&quot;)
##  
##                     Model Likelihood    Discrimination    
##                           Ratio Test           Indexes    
##  Obs       1384    LR chi2      9.18    R2       0.007    
##  Events     963    d.f.            1    Dxy      0.062    
##  sigma 1.101582    Pr(&gt; chi2) 0.0024    g        0.107    
##                                         gr       1.113    
##  
##              Coef    S.E.   Wald Z Pr(&gt;|Z|)
##  (Intercept)  5.0494 0.0538 93.87  &lt;0.0001 
##  sex=M       -0.2162 0.0716 -3.02  0.0025  
##  Log(scale)   0.0967 0.0278  3.48  0.0005  
## </code></pre>
<ul>
<li>P-value of 0.0025 provides strong evidence that the rate of death is higher in males than females.</li>
</ul>
<pre class="r"><code># HR for sex: M vs. F
exp(-coef(fit2)[2]/fit2$scale)</code></pre>
<pre><code>##    sex=M 
## 1.216865</code></pre>
<ul>
<li>The rate of death for males is 1.217 times the rate of death for females.</li>
</ul>
<pre class="r"><code># Survival time ratio
summary(fit2,sex=&quot;F&quot;)</code></pre>
<pre><code>##              Effects              Response : Surv(futime, death) 
## 
##  Factor               Low High Diff. Effect   S.E.     Lower 0.95 Upper 0.95
##  sex - M:F            1   2    NA    -0.21622 0.071609 -0.35669   -0.075742 
##   Survival Time Ratio 1   2    NA     0.80556       NA  0.69999    0.927060</code></pre>
<ul>
<li>The median survival time for males is 0.806 times the median survival time for females.</li>
</ul>
<pre class="r"><code>survplot(fit2,sex)
survplot(fit.km,add=TRUE,label.curves=FALSE,conf=&quot;none&quot;,col=&quot;red&quot;)</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-62-1.png" width="672" /></p>
</div>
<div id="question-4-3" class="section level2">
<h2>Question 4</h2>
<p>Which looks better (exponential or Weibull)?</p>
<pre class="r"><code>survplot(fit.km,conf=&quot;none&quot;)
survplot(fit1,sex,add=TRUE,label.curves=FALSE,col=&quot;red&quot;) # exponential
survplot(fit2,sex,add=TRUE,label.curves=FALSE,col=&quot;blue&quot;) # weibull</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-63-1.png" width="672" /></p>
<ul>
<li>There’s very little difference between the two models in this example. The AIC for the Weibull is slightly smaller, which may or may not mean anything.</li>
</ul>
</div>
<div id="question-5" class="section level2">
<h2>Question 5</h2>
<p>Fit a Cox model with sex as the covariate and interpret.</p>
<pre class="r"><code>print(fit1.cox &lt;- cph(Surv(futime,death)~sex,data=mgus2))</code></pre>
<pre><code>## Cox Proportional Hazards Model
##  
##  cph(formula = Surv(futime, death) ~ sex, data = mgus2)
##  
##                         Model Tests    Discrimination    
##                                               Indexes    
##  Obs      1384    LR chi2      9.68    R2       0.007    
##  Events    963    d.f.            1    Dxy      0.062    
##  Center 0.1098    Pr(&gt; chi2) 0.0019    g        0.100    
##                   Score chi2   9.65    gr       1.105    
##                   Pr(&gt; chi2) 0.0019                      
##  
##        Coef   S.E.   Wald Z Pr(&gt;|Z|)
##  sex=M 0.2017 0.0651 3.10   0.0019  
## </code></pre>
<pre class="r"><code>summary(fit1.cox,sex=&quot;F&quot;)</code></pre>
<pre><code>##              Effects              Response : Surv(futime, death) 
## 
##  Factor        Low High Diff. Effect  S.E.     Lower 0.95 Upper 0.95
##  sex - M:F     1   2    NA    0.20174 0.065062 0.074221   0.32926   
##   Hazard Ratio 1   2    NA    1.22350       NA 1.077000   1.38990</code></pre>
<ul>
<li>The rate of death for males is 1.224 times the rate of death for females.</li>
<li>There is strong evidence that the rate of death is higher in males than females (HR=1.22350; 95% CI: (1.07700,1.38990); p-value: 0.0019)</li>
</ul>
</div>
<div id="question-6" class="section level2">
<h2>Question 6</h2>
<p>Add age using a restricted cubic spline with 4 knots. Test it with a LRT and display results.</p>
<pre class="r"><code>print(fit2.cox &lt;- cph(Surv(futime,death)~sex+rcs(age,4),data=mgus2))</code></pre>
<pre><code>## Cox Proportional Hazards Model
##  
##  cph(formula = Surv(futime, death) ~ sex + rcs(age, 4), data = mgus2)
##  
##                        Model Tests    Discrimination    
##                                              Indexes    
##  Obs     1384    LR chi2    396.10    R2       0.249    
##  Events   963    d.f.            4    Dxy      0.334    
##  Center 3.248    Pr(&gt; chi2) 0.0000    g        0.838    
##                  Score chi2 408.99    gr       2.311    
##                  Pr(&gt; chi2) 0.0000                      
##  
##        Coef    S.E.   Wald Z Pr(&gt;|Z|)
##  sex=M  0.3605 0.0657  5.48  &lt;0.0001 
##  age    0.0380 0.0108  3.52  0.0004  
##  age&#39;   0.0473 0.0214  2.21  0.0272  
##  age&#39;&#39; -0.2396 0.1233 -1.94  0.0520  
## </code></pre>
<pre class="r"><code># LRT
lrtest(fit1.cox,fit2.cox)</code></pre>
<pre><code>## 
## Model 1: Surv(futime, death) ~ sex
## Model 2: Surv(futime, death) ~ sex + rcs(age, 4)
## 
## L.R. Chisq       d.f.          P 
##     386.42       3.00       0.00</code></pre>
<ul>
<li>We are testing the null hypothesis that the coefficients for the age variable are equal to 0, against the alternative hypothesis that at least one coefficient is not equal to 0.</li>
<li>Since the p-value is approximately 0.00, there is sufficient evidence to suggest that we should retain the age variable using a restricted cubic spline with 4 knots.</li>
</ul>
<pre class="r"><code># Adjusted effect for sex
summary(fit2.cox,sex=&quot;F&quot;)</code></pre>
<pre><code>##              Effects              Response : Surv(futime, death) 
## 
##  Factor        Low High Diff. Effect  S.E.     Lower 0.95 Upper 0.95
##  age           63  79   16    1.13420 0.094988 0.94802    1.32040   
##   Hazard Ratio 63  79   16    3.10870       NA 2.58060    3.74480   
##  sex - M:F      1   2   NA    0.36049 0.065742 0.23164    0.48935   
##   Hazard Ratio  1   2   NA    1.43400       NA 1.26070    1.63120</code></pre>
<ul>
<li>The rate of death for 79-year-olds is 3.109 times the rate of death for 63-year-olds when adjusted for <code>sex</code>.</li>
<li>There is strong evidence that the rate of death is higher in 79-year-olds than 63-year-olds (HR=3.10870; 95% CI: (2.58060,3.74480), p-value: 0.0004)</li>
<li>The rate of death for males is 1.434 times the rate of death for females when adjusted for <code>age</code>.</li>
<li>There is strong evidence that the rate of death is higher in males than females (HR=1.43400; 95% CI: (1.26070,1.63120); p-value: &lt;0.0001)</li>
</ul>
<pre class="r"><code># You can specify the specific age groups
summary(fit2.cox,sex=&quot;F&quot;,age=c(40,80))</code></pre>
<pre><code>##              Effects              Response : Surv(futime, death) 
## 
##  Factor        Low High Diff. Effect  S.E.     Lower 0.95 Upper 0.95
##  age           40  80   40    2.16870 0.194200 1.78810     2.54930  
##   Hazard Ratio 40  80   40    8.74700       NA 5.97800    12.79800  
##  sex - M:F      1   2   NA    0.36049 0.065742 0.23164     0.48935  
##   Hazard Ratio  1   2   NA    1.43400       NA 1.26070     1.63120</code></pre>
<ul>
<li>The rate of death for 80-year-olds is 8.747 times the rate of death for 40-year-olds.</li>
<li>Note that the hazard ratio for <code>sex</code> remains unchanged.</li>
</ul>
<pre class="r"><code># Plot of age effect
plot(Predict(fit2.cox,age,sex))</code></pre>
<p><img src="CHL5202_files/figure-html/unnamed-chunk-70-1.png" width="672" /></p>
<ul>
<li>The vertical distance between the two curves remain constant throughout as that represents the <code>sex</code> effect.</li>
<li>The curves both fluctuate together depending on the <code>age</code>.</li>
</ul>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
